version: '3'
services:
  flyway:
    image: narutosimaha/flyway-langchat
    environment:
      - LANGCHAT_DB=langchat
      - LANGCHAT_URL=jdbc:postgresql://langdb:5432
      - POSTGRES_USER=langteam
      - POSTGRES_PASSWORD=Aa1234
    # entrypoint: /bin/bash
    # command: [
    #   "-c",
    #   "/flyway/flyway -url=$$LANGCHAT_DB_URL/$$LANGCHAT_DB -user=$$POSTGRES_USER -password=$$POSTGRES_PASSWORD -connectRetries=60 migrate"
    # ]
    depends_on:
      - langdb

  langdb:
    image: postgres
    environment:
      - POSTGRES_DB=langchat
      - POSTGRES_USER=langteam
      - POSTGRES_PASSWORD=Aa1234
    ports:
      - 5434:5432
    volumes:
      - langchat:/var/lib/postgresql/data
    restart: always

volumes:
  langchat: