ALTER TABLE Users
ALTER COLUMN is_tutor TYPE BOOLEAN DEFAULT FALSE,
ALTER COLUMN is_restrict TYPE BOOLEAN DEFAULT FALSE,
ALTER COLUMN is_removed TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE ChatConf
ALTER COLUMN isMute TYPE BOOLEAN DEFAULT FALSE,
ALTER COLUMN isBlock TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE Arrangement
ALTER COLUMN is_accepted TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE Relationship
ALTER COLUMN type TYPE BOOLEAN;

ALTER TABLE Groups
ALTER COLUMN is_public TYPE BOOLEAN DEFAULT TRUE,
ALTER COLUMN post_check TYPE BOOLEAN DEFAULT FALSE,
ALTER COLUMN is_removed TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE GroupMember
ALTER COLUMN is_removed TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE JoinGrpReq
ALTER COLUMN is_removed TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE Post
ALTER COLUMN is_audio TYPE BOOLEAN DEFAULT FALSE,
ALTER COLUMN is_image TYPE BOOLEAN DEFAULT FALSE,
ALTER COLUMN is_group TYPE BOOLEAN DEFAULT FALSE,
ALTER COLUMN is_room TYPE BOOLEAN DEFAULT FALSE,
ALTER COLUMN is_share TYPE BOOLEAN DEFAULT FALSE,
ALTER COLUMN is_public TYPE BOOLEAN DEFAULT TRUE,
ALTER COLUMN is_video TYPE BOOLEAN DEFAULT TRUE,
ALTER COLUMN is_removed TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE GroupPost
ALTER COLUMN is_qualified TYPE BOOLEAN DEFAULT TRUE,
ALTER COLUMN is_hidden TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE AudioRoom
ALTER COLUMN is_closed TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE VocabPackage
ALTER COLUMN is_public TYPE BOOLEAN DEFAULT TRUE,
ALTER COLUMN is_shared TYPE BOOLEAN DEFAULT TRUE,
ALTER COLUMN is_removed TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE Vocabulary
ALTER COLUMN is_removed TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE Topic
ALTER COLUMN is_public TYPE BOOLEAN DEFAULT TRUE,
ALTER COLUMN is_removed TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE PostTopic
ALTER COLUMN is_removed TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE VocabPackage
ALTER COLUMN is_image TYPE BOOLEAN DEFAULT FALSE,
ALTER COLUMN is_correct TYPE BOOLEAN DEFAULT FALSE,
ALTER COLUMN is_audio TYPE BOOLEAN DEFAULT FALSE,
ALTER COLUMN is_removed TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE Punishment
ALTER COLUMN is_restrict TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE GroupOpReq
ALTER COLUMN is_qualified TYPE BOOLEAN DEFAULT FALSE;

ALTER TABLE TutorReq
ALTER COLUMN is_qualified TYPE BOOLEAN DEFAULT FALSE;