ALTER TABLE Users
ALTER COLUMN is_tutor DROP DEFAULT,
ALTER COLUMN is_restrict DROP DEFAULT,
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_tutor TYPE boolean SET DEFAULT FALSE,
ALTER COLUMN is_restrict TYPE boolean SET DEFAULT FALSE,
ALTER COLUMN is_removed TYPE boolean SET DEFAULT FALSE;

ALTER TABLE ChatConf
ALTER COLUMN isMute DROP DEFAULT,
ALTER COLUMN isBlock DROP DEFAULT,
ALTER COLUMN isMute TYPE boolean SET DEFAULT FALSE,
ALTER COLUMN isBlock TYPE boolean SET DEFAULT FALSE;

ALTER TABLE Arrangement
ALTER COLUMN is_accepted DROP DEFAULT,
ALTER COLUMN is_accepted TYPE boolean SET DEFAULT FALSE;

ALTER TABLE Relationship
ALTER COLUMN type TYPE boolean;

ALTER TABLE Groups
ALTER COLUMN is_public DROP DEFAULT,
ALTER COLUMN post_check DROP DEFAULT,
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_public TYPE boolean SET DEFAULT TRUE,
ALTER COLUMN post_check TYPE boolean SET DEFAULT FALSE,
ALTER COLUMN is_removed TYPE boolean SET DEFAULT FALSE;

ALTER TABLE GroupMember
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_removed TYPE boolean SET DEFAULT FALSE;

ALTER TABLE JoinGrpReq
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_removed TYPE boolean SET DEFAULT FALSE;

ALTER TABLE Post
ALTER COLUMN is_audio DROP DEFAULT,
ALTER COLUMN is_image DROP DEFAULT,
ALTER COLUMN is_group DROP DEFAULT,
ALTER COLUMN is_room DROP DEFAULT,
ALTER COLUMN is_share DROP DEFAULT,
ALTER COLUMN is_public DROP DEFAULT,
ALTER COLUMN is_video DROP DEFAULT,
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_audio TYPE boolean SET DEFAULT FALSE,
ALTER COLUMN is_image TYPE boolean SET DEFAULT FALSE,
ALTER COLUMN is_group TYPE boolean SET DEFAULT FALSE,
ALTER COLUMN is_room TYPE boolean SET DEFAULT FALSE,
ALTER COLUMN is_share TYPE boolean SET DEFAULT FALSE,
ALTER COLUMN is_public TYPE boolean SET DEFAULT TRUE,
ALTER COLUMN is_video TYPE boolean SET DEFAULT TRUE,
ALTER COLUMN is_removed TYPE boolean SET DEFAULT FALSE;

ALTER TABLE GroupPost
ALTER COLUMN is_qualified DROP DEFAULT,
ALTER COLUMN is_hidden DROP DEFAULT,
ALTER COLUMN is_qualified TYPE boolean SET DEFAULT TRUE,
ALTER COLUMN is_hidden TYPE boolean SET DEFAULT FALSE;

ALTER TABLE AudioRoom
ALTER COLUMN is_closed DROP DEFAULT,
ALTER COLUMN is_closed TYPE boolean SET DEFAULT FALSE;

ALTER TABLE VocabPackage
ALTER COLUMN is_public DROP DEFAULT,
ALTER COLUMN is_shared DROP DEFAULT,
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_public TYPE boolean SET DEFAULT TRUE,
ALTER COLUMN is_shared TYPE boolean SET DEFAULT TRUE,
ALTER COLUMN is_removed TYPE boolean SET DEFAULT FALSE;

ALTER TABLE Vocabulary
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_removed TYPE boolean SET DEFAULT FALSE;

ALTER TABLE Topic
ALTER COLUMN is_public DROP DEFAULT,
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_public TYPE boolean SET DEFAULT TRUE,
ALTER COLUMN is_removed TYPE boolean SET DEFAULT FALSE;

ALTER TABLE PostTopic
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_removed TYPE boolean SET DEFAULT FALSE;

ALTER TABLE VocabPackage
ALTER COLUMN is_image DROP DEFAULT,
ALTER COLUMN is_correct DROP DEFAULT,
ALTER COLUMN is_audio DROP DEFAULT,
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_image TYPE boolean SET DEFAULT FALSE,
ALTER COLUMN is_correct TYPE boolean SET DEFAULT FALSE,
ALTER COLUMN is_audio TYPE boolean SET DEFAULT FALSE,
ALTER COLUMN is_removed TYPE boolean SET DEFAULT FALSE;

ALTER TABLE Punishment
ALTER COLUMN is_restrict DROP DEFAULT,
ALTER COLUMN is_restrict TYPE boolean SET DEFAULT FALSE;

ALTER TABLE GroupOpReq
ALTER COLUMN is_qualified DROP DEFAULT,
ALTER COLUMN is_qualified TYPE boolean SET DEFAULT FALSE;

ALTER TABLE TutorReq
ALTER COLUMN is_qualified DROP DEFAULT,
ALTER COLUMN is_qualified TYPE boolean SET DEFAULT FALSE;