ALTER TABLE Users
ALTER COLUMN is_tutor DROP DEFAULT,
ALTER COLUMN is_restrict DROP DEFAULT,
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_tutor TYPE BOOLEAN SET DEFAULT FALSE,
ALTER COLUMN is_restrict TYPE BOOLEAN SET DEFAULT FALSE,
ALTER COLUMN is_removed TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE ChatConf
ALTER COLUMN isMute DROP DEFAULT,
ALTER COLUMN isBlock DROP DEFAULT,
ALTER COLUMN isMute TYPE BOOLEAN SET DEFAULT FALSE,
ALTER COLUMN isBlock TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE Arrangement
ALTER COLUMN is_accepted DROP DEFAULT,
ALTER COLUMN is_accepted TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE Relationship
ALTER COLUMN type TYPE BOOLEAN;

ALTER TABLE Groups
ALTER COLUMN is_public DROP DEFAULT,
ALTER COLUMN post_check DROP DEFAULT,
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_public TYPE BOOLEAN SET DEFAULT TRUE,
ALTER COLUMN post_check TYPE BOOLEAN SET DEFAULT FALSE,
ALTER COLUMN is_removed TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE GroupMember
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_removed TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE JoinGrpReq
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_removed TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE Post
ALTER COLUMN is_audio DROP DEFAULT,
ALTER COLUMN is_image DROP DEFAULT,
ALTER COLUMN is_group DROP DEFAULT,
ALTER COLUMN is_room DROP DEFAULT,
ALTER COLUMN is_share DROP DEFAULT,
ALTER COLUMN is_public DROP DEFAULT,
ALTER COLUMN is_video DROP DEFAULT,
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_audio TYPE BOOLEAN SET DEFAULT FALSE,
ALTER COLUMN is_image TYPE BOOLEAN SET DEFAULT FALSE,
ALTER COLUMN is_group TYPE BOOLEAN SET DEFAULT FALSE,
ALTER COLUMN is_room TYPE BOOLEAN SET DEFAULT FALSE,
ALTER COLUMN is_share TYPE BOOLEAN SET DEFAULT FALSE,
ALTER COLUMN is_public TYPE BOOLEAN SET DEFAULT TRUE,
ALTER COLUMN is_video TYPE BOOLEAN SET DEFAULT TRUE,
ALTER COLUMN is_removed TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE GroupPost
ALTER COLUMN is_qualified DROP DEFAULT,
ALTER COLUMN is_hidden DROP DEFAULT,
ALTER COLUMN is_qualified TYPE BOOLEAN SET DEFAULT TRUE,
ALTER COLUMN is_hidden TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE AudioRoom
ALTER COLUMN is_closed DROP DEFAULT,
ALTER COLUMN is_closed TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE VocabPackage
ALTER COLUMN is_public DROP DEFAULT,
ALTER COLUMN is_shared DROP DEFAULT,
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_public TYPE BOOLEAN SET DEFAULT TRUE,
ALTER COLUMN is_shared TYPE BOOLEAN SET DEFAULT TRUE,
ALTER COLUMN is_removed TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE Vocabulary
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_removed TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE Topic
ALTER COLUMN is_public DROP DEFAULT,
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_public TYPE BOOLEAN SET DEFAULT TRUE,
ALTER COLUMN is_removed TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE PostTopic
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_removed TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE VocabPackage
ALTER COLUMN is_image DROP DEFAULT,
ALTER COLUMN is_correct DROP DEFAULT,
ALTER COLUMN is_audio DROP DEFAULT,
ALTER COLUMN is_removed DROP DEFAULT,
ALTER COLUMN is_image TYPE BOOLEAN SET DEFAULT FALSE,
ALTER COLUMN is_correct TYPE BOOLEAN SET DEFAULT FALSE,
ALTER COLUMN is_audio TYPE BOOLEAN SET DEFAULT FALSE,
ALTER COLUMN is_removed TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE Punishment
ALTER COLUMN is_restrict DROP DEFAULT,
ALTER COLUMN is_restrict TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE GroupOpReq
ALTER COLUMN is_qualified DROP DEFAULT,
ALTER COLUMN is_qualified TYPE BOOLEAN SET DEFAULT FALSE;

ALTER TABLE TutorReq
ALTER COLUMN is_qualified DROP DEFAULT,
ALTER COLUMN is_qualified TYPE BOOLEAN SET DEFAULT FALSE;