name: Auto-migration
on:
  push:
    branches:
      - prod
jobs:
  general:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: ${{ secrets.GENERAL_URL }}
          user: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          locations: ./db/sql/langeneral
      - run: echo 'testing'

  tracking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: ${{ secrets.TRACKING_URL }}
          user: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          locations: ./db/sql/langtracking
      - run: echo 'testing'
